In [1]:
import pandas as pd
import numpy as np


In [33]:
url = 'https://raw.githubusercontent.com/rafaelpuyau/infinity_school/main/ds/datasets/atividade_casa.csv'


In [26]:
# Atividade 01 da aula 03
arr = np.arange(5, 21, 5)

arr2 = np.arange(1, 6)

print(arr) 
print(arr2)



[ 5 10 15 20]
[1 2 3 4 5]


In [32]:
# Atividade 02 da aula 03 
print(np.sqrt(arr))
print(arr2 + 3)


[2.23606798 3.16227766 3.87298335 4.47213595]
[4 5 6 7 8]


In [37]:
# atividade 03 pratica da aula 03
df = pd.read_csv(url)

df

df['Data da Venda'] = pd.to_datetime(df['Data da Venda'])

df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 8 columns):
 #   Column         Non-Null Count   Dtype         
---  ------         --------------   -----         
 0   Produto        100000 non-null  object        
 1   Cor            100000 non-null  object        
 2   Valor          100000 non-null  float64       
 3   Quantidade     100000 non-null  int64         
 4   Sexo           100000 non-null  object        
 5   Idade          100000 non-null  int64         
 6   Data da Venda  100000 non-null  datetime64[ns]
 7   Canal          100000 non-null  object        
dtypes: datetime64[ns](1), float64(1), int64(2), object(4)
memory usage: 6.1+ MB
