In [5]:
import pandas as pd
import numpy as np


In [6]:
url = 'https://raw.githubusercontent.com/rafaelpuyau/infinity_school/main/ds/datasets/atividade_casa.csv'


In [7]:
# Atividade 01 da aula 03
arr = np.arange(5, 21, 5)

arr2 = np.arange(1, 6)

print(arr) 
print(arr2)



[ 5 10 15 20]
[1 2 3 4 5]


In [8]:
# Atividade 02 da aula 03 
print(np.sqrt(arr))
print(arr2 + 3)


[2.23606798 3.16227766 3.87298335 4.47213595]
[4 5 6 7 8]


In [9]:
# atividade 03 pratica da aula 03
df = pd.read_csv(url)

df['Data da Venda'] = pd.to_datetime(df['Data da Venda'])

df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 8 columns):
 #   Column         Non-Null Count   Dtype         
---  ------         --------------   -----         
 0   Produto        100000 non-null  object        
 1   Cor            100000 non-null  object        
 2   Valor          100000 non-null  float64       
 3   Quantidade     100000 non-null  int64         
 4   Sexo           100000 non-null  object        
 5   Idade          100000 non-null  int64         
 6   Data da Venda  100000 non-null  datetime64[ns]
 7   Canal          100000 non-null  object        
dtypes: datetime64[ns](1), float64(1), int64(2), object(4)
memory usage: 6.1+ MB


In [10]:
df


Produto      Cor       Valor  Quantidade       Sexo  Idade  \
0         Calça     Roxa   66.947509           4  Masculino     39   
1      Camiseta  Amarela   99.692292           1  Masculino     30   
2         Calça     Azul   92.502413           2   Feminino     25   
3         Short     Azul  162.693470           1   Feminino     45   
4      Camiseta  Laranja  148.191049           3   Feminino     29   
...         ...      ...         ...         ...        ...    ...   
99995     Calça  Laranja  101.158897           4  Masculino     46   
99996      Saia    Preta  100.815311           3  Masculino     28   
99997     Calça     Azul   63.924217           4   Feminino     48   
99998     Calça     Azul  149.062392           3   Feminino     19   
99999      Saia    Verde  114.089710           3  Masculino     25   

      Data da Venda         Canal  
0        2022-02-25  Loja Virtual  
1        2022-01-19   Loja Física  
2        2022-03-11   Loja Física  
3        2022-05-01   Loja Física  
4        2022-03-13   Loja Física  
...             ...           ...  
99995    2022-01-24   Loja Física  
99996    2022-03-08   Loja Física  
99997    2022-06-08  Loja Virtual  
99998    2022-01-05   Loja Física  
99999    2022-04-19  Loja Virtual  

[100000 rows x 8 columns]

In [13]:


df.iloc[


Produto                        Short
Cor                             Azul
Valor                      162.69347
Quantidade                         1
Sexo                        Feminino
Idade                             45
Data da Venda    2022-05-01 00:00:00
Canal                    Loja Física
Name: 3, dtype: object